//
//  ToolbarRouter.swift
//  PlayCenter
//
//  Created by Behrad Kazemi on 8/14/20.
//  Copyright (c) 2020 Behrad Kazemi. All rights reserved.
//
//  This file was generated by the BEK module generator.
//

import UIKit
import Domain
import SwiftUI

final class ToolbarRouter: Router {
  
  var hostingViewController: UIHostingController<ToolbarView>?
  // MARK: - Initialization
  
  func makeModule() -> UIHostingController<ToolbarView> {
    return ToolbarRouter.createModule(router: self)
  }
  
  static func createModule(router: ToolbarRouter) -> UIHostingController<ToolbarView> {
    let viewModel = ToolbarViewModel(router: router)
    let view = ToolbarView(viewModel: viewModel)
    router.hostingViewController = UIHostingController(rootView: view)
    router.baseViewController = router.hostingViewController
    return router.hostingViewController!
  }
  
  //  MARK: - Functions
  
}

