//
//  CircularArtworkViewModel.swift
//  PlayCenter
//
//  Created by Behrad Kazemi on 8/14/20.
//  Copyright (c) 2020 Behrad Kazemi. All rights reserved.
//
//  This file was generated by the BEK module generator.
//

import Combine
import Domain
import UIKit

class CircularArtworkViewModel: ObservableObject {
  
  //MARK: - Properties
  var data: Data?
  var shadow = CGFloat(10.0)
  var lineWidth = CGFloat(3.0)
  var hasShadow = true
  private var cancellableSet: Set<AnyCancellable> = []
  
  //MARK: - Initialize
  init(model: Data?, shadow: CGFloat = CGFloat(10.0), lineWidth: CGFloat = CGFloat(3.0), hasShadow: Bool = true) {
    self.data = model
    self.lineWidth = lineWidth
    self.shadow = shadow
    self.hasShadow = hasShadow
  }
  
  //MARK: - functions

}
