//
//  UpNextSongsRouter.swift
//  PlayCenter
//
//  Created by Behrad Kazemi on 8/12/20.
//  Copyright (c) 2020 Behrad Kazemi. All rights reserved.
//
//  This file was generated by the BEK module generator.
//

import UIKit
import SwiftUI
import Domain

final class UpNextSongsRouter: Router {
  
  // MARK: - Initialization
  func makeModule() -> UIViewController {
    return UpNextSongsRouter.createModule(router: self)
  }
  
  static func createModule(router: UpNextSongsRouter) -> UIViewController {
    let viewModel = UpNextVM(router: router)
    let view = UpNextSongsView(viewModel: viewModel)
    router.baseViewController = UIHostingController(rootView: view)
    return router.baseViewController!
  }
  
  //  MARK: - Functions
  
  
}

