//
//  ListPlaceholderViewModel.swift
//  PlayCenter
//
//  Created by Behrad Kazemi on 8/29/20.
//  Copyright (c) 2020 Behrad Kazemi. All rights reserved.
//
//  This file was generated by the BEK module generator.
//

import Combine
import Domain

class ListPlaceholderViewModel: ObservableObject {
  
  //MARK: - Properties
  var router: ListPlaceholderRouter
  let useCases: iTunesSongsUseCases
  let types: [ListPlaceholderType]
  private var cancellableSet: Set<AnyCancellable> = []
  
  //MARK: - Initialize
  init(router: ListPlaceholderRouter, types: [ListPlaceholderType]) {
    self.router = router
    self.useCases = router.platforms.iTunesKit
    self.router = router
    self.types = types
  }
  
  //MARK: - functions
  
//  func (<#parameters#>) -> <#return type#> {
//    <#function body#>
//  }
}
