//
//  FindViewModel.swift
//  PlayCenter
//
//  Created by Behrad Kazemi on 9/18/20.
//  Copyright (c) 2020 Behrad Kazemi. All rights reserved.
//
//  This file was generated by the BEK module generator.
//

import Combine
import Domain

class FindViewModel: ObservableObject {
  
  //MARK: - Properties
  var router: FindRouter
  
  private var cancellableSet: Set<AnyCancellable> = []
  
  //MARK: - Initialize
  init(router: FindRouter) {
    self.router = router

    self.router = router
    self.setup()
  }
  
  //MARK: - Setup
   func setup(){

  }
  
  //MARK: - functions

}
