//
//  FindRouter.swift
//  PlayCenter
//
//  Created by Behrad Kazemi on 9/18/20.
//  Copyright (c) 2020 Behrad Kazemi. All rights reserved.
//
//  This file was generated by the BEK module generator.
//

import UIKit
import Domain
import SwiftUI

final class FindRouter: Router {
  
  var hostingViewController: UIHostingController<FindView>?
  
  // MARK: - Initialization
  
  func makeModule() -> UIHostingController<FindView> {
    return FindRouter.createModule(router: self)
  }
  
  static func createModule(router: FindRouter) -> UIHostingController<FindView> {
    let viewModel = FindViewModel(router: router)
    let view = FindView(viewModel: viewModel)
    router.hostingViewController = UIHostingController(rootView: view)
    router.baseViewController = router.hostingViewController
    return router.hostingViewController!
  }
  
  //  MARK: - Functions
  
  
}

