//
//  FindView.swift
//  PlayCenter
//
//  Created by Behrad Kazemi on 9/18/20.
//  Copyright (c) 2020 Behrad Kazemi. All rights reserved.
//
//  This file was generated by the BEK module generator.
//

import SwiftUI

struct FindView: View {
  
  // MARK: -  Properties
  @ObservedObject var viewModel: FindViewModel
  @State var scrollViewOffset: CGFloat = 0.0
  init(viewModel: FindViewModel){
    self.viewModel = viewModel

  }
  
  var body: some View {
    ScrollView(.vertical, showsIndicators: false, content: {
      
    })
      GeometryReader { proxy in
        ZStack(alignment: .leading){
          TrackableScrollView(.vertical, showIndicators: true, contentOffset: $scrollViewOffset) {
            Spacer()
             .frame(height: 48, alignment: .center)
             .padding(.horizontal, 24)
              .padding(.top, proxy.safeAreaInsets.top)
              .hidden()
            Text("Categories")
              .font(.title)
              .fontWeight(.bold)
              .multilineTextAlignment(.leading)
              .foregroundColor(.white)
              .padding(.all, 24)
          }.edgesIgnoringSafeArea(.all)
          
          
          VStack(alignment: .center, content: {
            SearchBar()
             .frame(height: 48, alignment: .center)
             .padding(.horizontal, 24)
            
            Spacer()
          })
        }.frame(width: proxy.size.width)

      }
  }
}

struct FindView_Previews: PreviewProvider {
  static var previews: some View {
    ZStack(alignment: .center, content: {
      Rectangle().foregroundColor(Color.black.opacity(0.3)).edgesIgnoringSafeArea(.all)
      FindView(viewModel: FindViewModel(router: FindRouter(platforms: Application.shared.package)))
    })
  }
}
