//
//  ControlCenterRouter.swift
//  PlayCenter
//
//  Created by Behrad Kazemi on 8/9/20.
//  Copyright (c) 2020 Behrad Kazemi. All rights reserved.
//
//  This file was generated by the BEK module generator.
//

import UIKit
import Domain
import SwiftUI

final class ControlCenterRouter: Router {
  
  var hostingViewController: UIHostingController<ControlCenterView>?
  
  // MARK: - Initialization
  func makeModule() -> UIHostingController<ControlCenterView>{
    return ControlCenterRouter.createModule(router: self)
  }
  
  static func createModule(router: ControlCenterRouter) -> UIHostingController<ControlCenterView> {
    let viewModel = ControlCenterVM(router: router)
    let view = ControlCenterView(viewModel: viewModel)
    router.hostingViewController = UIHostingController(rootView: view)
    router.baseViewController = router.hostingViewController
    return router.hostingViewController!
  }
  
  //  MARK: - Functions
  func showUpNext() {
    if let safeBaseController = self.baseViewController {
      let upNextModule = UpNextSongsRouter(platforms: platforms).makeModule()
      safeBaseController.present(upNextModule, animated: true, completion: nil)
    }
  }
  
}

