//
//  ControlCenterRouter.swift
//  PlayCenter
//
//  Created by Behrad Kazemi on 8/9/20.
//  Copyright (c) 2020 Behrad Kazemi. All rights reserved.
//
//  This file was generated by the BEK module generator.
//

import UIKit
import Domain
import SwiftUI

final class ControlCenterRouter: Router {
  
  // MARK: - Initialization
  
  static func createModule(router: ControlCenterRouter) -> UIViewController {
    let viewModel = ControlCenterVM(router: router)
    let view = ControlCenterView()
    v
    return UIHostingController(rootView: view)
  }
  
  //  MARK: - Functions
  func showUpNext() {
    
  }
  
}

